services:
  subscribers:
    security.subscriber:
      class: \App\EventSubscriber\LoginActionSubscriber
      register_route_feedback:
        App\Controller\SecurityController::indexAction:
          msg: Welcome you are now logged in

    registration.subscriber:
      class: \App\EventSubscriber\RegistrationActionSubscriber
      register_route_feedback:
        App\Controller\RegistrationController::registerAction:
          msg: You are now registered