# Specifies the directory which contains non dynamic routes . ie the routes which
# are defined within this config file
# App/Templates/client/**
# Note client is the default directory
client_dir: client
# The main directory which holds all our .twig template files. This directory
# should have the sub-directory 'client' defined above
template_dir: Templates

"":
  controller: home
  action: index

login:
  controller: security
  action: index